// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADiNqNSMt3TFTCS8O7cxB-h3-ypmgpkwo',
    appId: '1:497114424894:web:2415e80d9c59df6dbdd36f',
    messagingSenderId: '497114424894',
    projectId: 'first-assignment-e6e6a',
    authDomain: 'first-assignment-e6e6a.firebaseapp.com',
    databaseURL: 'https://first-assignment-e6e6a-default-rtdb.firebaseio.com',
    storageBucket: 'first-assignment-e6e6a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4wPvS29qZFDE1A7gpKRUDB26RwfJWjzo',
    appId: '1:497114424894:android:c7a7203c3e0d0d3ebdd36f',
    messagingSenderId: '497114424894',
    projectId: 'first-assignment-e6e6a',
    databaseURL: 'https://first-assignment-e6e6a-default-rtdb.firebaseio.com',
    storageBucket: 'first-assignment-e6e6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVj1rpDTDIBq0GwZJox2eCspDu2cFCg2I',
    appId: '1:497114424894:ios:a4ea5f471ab290c3bdd36f',
    messagingSenderId: '497114424894',
    projectId: 'first-assignment-e6e6a',
    databaseURL: 'https://first-assignment-e6e6a-default-rtdb.firebaseio.com',
    storageBucket: 'first-assignment-e6e6a.appspot.com',
    iosBundleId: 'com.example.firstAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVj1rpDTDIBq0GwZJox2eCspDu2cFCg2I',
    appId: '1:497114424894:ios:4dceb03ce804b5ecbdd36f',
    messagingSenderId: '497114424894',
    projectId: 'first-assignment-e6e6a',
    databaseURL: 'https://first-assignment-e6e6a-default-rtdb.firebaseio.com',
    storageBucket: 'first-assignment-e6e6a.appspot.com',
    iosBundleId: 'com.example.firstAssignment.RunnerTests',
  );
}
